"""Generic course runner for minimal regression and stress worlds.

The robot, LiDAR, odometry adapter, planner and control arbitration are the
same as in avoidance_extended_controller.py; only the route comes from the
robot's customData (generated by tools/build_avoidance_courses.py):

    course=<name> start=x,y,yaw wp=x,y|x,y|... max=<s> stall=<s>

Pass/fail criteria match the Extended benchmark: waypoint acceptance 0.14 m
(odometry pose), contact = any robot contact point above 1 cm, stall = no
0.04 m improvement of the true distance to the current waypoint for
``stall`` seconds, timeout = ``max`` seconds.  Additional diagnostics:

* recovery_entries: transitions into a recovery phase, backoff or
  front-corner escape;
* max_turn_flips: most left/right command reversals (|w| > 0.15 rad/s)
  inside any 3 s window;
* oscillation_events: 3 s windows with >= 6 reversals while the robot moved
  less than 0.10 m (persistent left-right oscillation).
"""

from collections import deque
import json
import math
import os
import sys
import tempfile
import time
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from avoidance import DynamicWindowAvoidance
from config import TIME_STEP, WHEEL_RADIUS, WHEEL_TRACK
from main import goal_in_robot_frame, nominal_waypoint_command, select_control_command
from practice_odometry import EncoderPose
from robot_io import RobotIO
from tools.avoidance_trace import TraceWriter


ACCEPTANCE = 0.14
OSCILLATION_WINDOW = 3.0
OSCILLATION_FLIPS = 6
OSCILLATION_DISPLACEMENT = 0.10


def parse_course(text):
    settings = dict(token.split("=", 1) for token in text.split() if "=" in token)
    start = tuple(float(value) for value in settings["start"].split(","))
    waypoints = tuple(
        tuple(float(value) for value in item.split(","))
        for item in settings["wp"].split("|")
    )
    return (
        settings.get("course", "course"),
        start,
        waypoints,
        float(settings.get("max", "240")),
        float(settings.get("stall", "35")),
    )


def main():
    robot = Supervisor()
    node = robot.getSelf()
    name, start, waypoints, max_seconds, stall_seconds = parse_course(
        node.getField("customData").getSFString()
    )
    io = RobotIO(robot)
    planner = DynamicWindowAvoidance(lidar_field_of_view=io.lidar.getFov())
    odometry = EncoderPose(robot, start)
    node.enableContactPointsTracking(TIME_STEP, True)
    trace = TraceWriter()
    result_path = Path(
        os.environ.get("COURSE_RESULT_DIR", tempfile.gettempdir()),
        f"techweek-course-{name}.json",
    )

    index = 0
    contacts = 0
    touching = False
    best = float("inf")
    progress_time = 0.0
    recovery_entries = 0
    in_recovery = False
    turn_events = deque()
    last_turn = 0
    max_flips = 0
    oscillation_events = 0
    oscillating = False
    positions = deque()
    min_clearance = float("inf")
    compute_total = 0.0
    compute_max = 0.0
    steps = 0
    last_print = -1.0

    while robot.step(TIME_STEP) != -1:
        now = robot.getTime()
        truth_position = node.getPosition()
        orientation = node.getOrientation()
        truth = (truth_position[0], truth_position[1],
                 math.atan2(orientation[3], orientation[0]))
        pose = odometry.update()

        if index < len(waypoints) and math.dist(pose[:2], waypoints[index]) < ACCEPTANCE:
            print(f"[WAYPOINT] t={now:.2f} reached={index + 1}/{len(waypoints)}", flush=True)
            index += 1
            best = float("inf")
            progress_time = now

        contact_now = any(point.getPoint()[2] > 0.01 for point in node.getContactPoints(True))
        if contact_now and not touching:
            contacts += 1
            print(f"[CONTACT] t={now:.2f} truth={truth}", flush=True)
        touching = contact_now

        if index < len(waypoints):
            distance = math.dist(truth[:2], waypoints[index])
            if distance < best - 0.04:
                best = distance
                progress_time = now
        goal_reached = index == len(waypoints)
        stalled = not goal_reached and now - progress_time > stall_seconds
        timed_out = not goal_reached and now > max_seconds

        if goal_reached or stalled or timed_out or contacts:
            io.stop()
            result = {
                "course": name,
                "completed": goal_reached and contacts == 0,
                "goal_reached": goal_reached,
                "contacts": contacts,
                "stalled": stalled,
                "timed_out": timed_out,
                "seconds": round(now, 3),
                "reached_waypoints": index,
                "total_waypoints": len(waypoints),
                "recovery_entries": recovery_entries,
                "detours": getattr(planner, "detour_count", 0),
                "max_turn_flips": max_flips,
                "oscillation_events": oscillation_events,
                "min_lidar_clearance": round(min_clearance, 3),
                "planner_mean_ms": round(1000.0 * compute_total / max(1, steps), 3),
                "planner_max_ms": round(1000.0 * compute_max, 3),
            }
            result_path.write_text(json.dumps(result, indent=2), encoding="utf-8")
            print("[RESULT] " + json.dumps(result), flush=True)
            trace.close()
            robot.step(TIME_STEP)
            robot.simulationQuit(0 if result["completed"] else 1)
            break

        goal = waypoints[index]
        ranges = io.get_lidar()
        finite = [value for value in ranges if math.isfinite(value)]
        if finite:
            min_clearance = min(min_clearance, min(finite))
        local_goal = goal_in_robot_frame(goal, pose)
        started = time.perf_counter()
        avoidance_command = planner.choose_action(ranges, local_goal, pose=pose, sim_time=now)
        command = select_control_command(
            planner, nominal_waypoint_command(local_goal), avoidance_command
        )
        elapsed = time.perf_counter() - started
        compute_total += elapsed
        compute_max = max(compute_max, elapsed)
        steps += 1
        left, right, control = command
        io.set_wheel_speed(left, right)
        trace.record(now, pose, local_goal, ranges, command, io.lidar.getFov(), truth)

        recovering = (
            planner.recovery_phase is not None
            or planner.backoff_steps > 0
            or getattr(planner, "_front_corner_escape_active", False)
        )
        if recovering and not in_recovery:
            recovery_entries += 1
        in_recovery = recovering

        yaw_rate = WHEEL_RADIUS * (right - left) / WHEEL_TRACK
        turn = 1 if yaw_rate > 0.15 else -1 if yaw_rate < -0.15 else 0
        if turn and last_turn and turn != last_turn:
            turn_events.append(now)
        if turn:
            last_turn = turn
        positions.append((now, truth[0], truth[1]))
        while turn_events and now - turn_events[0] > OSCILLATION_WINDOW:
            turn_events.popleft()
        while positions and now - positions[0][0] > OSCILLATION_WINDOW:
            positions.popleft()
        max_flips = max(max_flips, len(turn_events))
        moved = math.dist(positions[0][1:], positions[-1][1:])
        now_oscillating = len(turn_events) >= OSCILLATION_FLIPS and moved < OSCILLATION_DISPLACEMENT
        if now_oscillating and not oscillating:
            oscillation_events += 1
            print(f"[OSCILLATION] t={now:.2f} flips={len(turn_events)} moved={moved:.3f}", flush=True)
        oscillating = now_oscillating

        if now - last_print >= 2.0:
            print(
                f"[RUN] t={now:.2f} wp={index} d={math.dist(pose[:2], goal):.2f} "
                f"truth=({truth[0]:.2f},{truth[1]:.2f},{truth[2]:.2f}) "
                f"control={control} action={avoidance_command[2]}",
                flush=True,
            )
            last_print = now


if __name__ == "__main__":
    from controller import Supervisor

    main()
